# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://daryna:password@db:5432/my_game
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=daryna
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_game

volumes:
  postgres_data: